import { Product, Category, VendorPublic } from '@/types';

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Tea & Spices',
    slug: 'tea-spices',
    description: 'Premium Ceylon tea, cinnamon, cardamom, and exotic spices',
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=300&fit=crop',
    parentId: null,
  },
  {
    id: 'cat-2',
    name: 'Textiles & Apparel',
    slug: 'textiles-apparel',
    description: 'Handloom fabrics, batik, silk, and designer clothing',
    imageUrl: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400&h=300&fit=crop',
    parentId: null,
  },
  {
    id: 'cat-3',
    name: 'Gems & Jewellery',
    slug: 'gems-jewellery',
    description: 'Ceylon sapphires, rubies, and handcrafted jewellery',
    imageUrl: 'https://images.unsplash.com/photo-1515562141589-67f0d569b6ac?w=400&h=300&fit=crop',
    parentId: null,
  },
  {
    id: 'cat-4',
    name: 'Handicrafts',
    slug: 'handicrafts',
    description: 'Traditional wood carvings, lacquerware, and pottery',
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=400&h=300&fit=crop',
    parentId: null,
  },
  {
    id: 'cat-5',
    name: 'Coconut Products',
    slug: 'coconut-products',
    description: 'Coconut oil, coir products, activated charcoal, and more',
    imageUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&h=300&fit=crop',
    parentId: null,
  },
  {
    id: 'cat-6',
    name: 'Electronics & Parts',
    slug: 'electronics-parts',
    description: 'Electronic components, PCB assemblies, and tech accessories',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=300&fit=crop',
    parentId: null,
  },
  {
    id: 'cat-7',
    name: 'Ayurveda & Wellness',
    slug: 'ayurveda-wellness',
    description: 'Natural remedies, herbal supplements, and wellness products',
    imageUrl: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400&h=300&fit=crop',
    parentId: null,
  },
  {
    id: 'cat-8',
    name: 'Food & Beverages',
    slug: 'food-beverages',
    description: 'Packaged foods, snacks, sauces, and specialty beverages',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop',
    parentId: null,
  },
];

export const mockVendors: VendorPublic[] = [
  {
    id: 'v-1',
    businessName: 'Ceylon Spice Gardens',
    businessSlug: 'ceylon-spice-gardens',
    description: 'Premium organic spices from the hills of Sri Lanka',
    logoUrl: null,
    bannerUrl: null,
    isVerified: true,
    averageRating: 4.8,
    totalReviews: 342,
    country: 'LK',
    city: 'Kandy',
  },
  {
    id: 'v-2',
    businessName: 'Raj Textiles India',
    businessSlug: 'raj-textiles-india',
    description: 'Finest handloom silks and cotton fabrics from Tamil Nadu',
    logoUrl: null,
    bannerUrl: null,
    isVerified: true,
    averageRating: 4.6,
    totalReviews: 218,
    country: 'IN',
    city: 'Chennai',
  },
  {
    id: 'v-3',
    businessName: 'Lanka Gems Co.',
    businessSlug: 'lanka-gems-co',
    description: 'Certified precious and semi-precious gemstones',
    logoUrl: null,
    bannerUrl: null,
    isVerified: true,
    averageRating: 4.9,
    totalReviews: 156,
    country: 'LK',
    city: 'Ratnapura',
  },
];

export const mockProducts: Product[] = [
  {
    id: 'p-1',
    name: 'Premium Ceylon Cinnamon Sticks - Grade Alba',
    slug: 'premium-ceylon-cinnamon-alba',
    description:
      'Authentic Ceylon cinnamon (Cinnamomum verum) hand-harvested from our plantation in Galle. Grade Alba is the finest grade with paper-thin bark and a delicate, sweet flavour. Perfect for gourmet cooking, baking, and beverages. USDA Organic certified.',
    shortDescription: 'Finest grade Ceylon cinnamon, hand-harvested and organic certified',
    baseCurrency: 'USD',
    basePrice: 24.99,
    compareAtPrice: 34.99,
    averageRating: 4.8,
    totalReviews: 127,
    minOrderQty: 1,
    vendorId: 'v-1',
    categoryId: 'cat-1',
    status: 'ACTIVE',
    images: [
      { id: 'img-1', url: 'https://images.unsplash.com/photo-1599909533706-bfa4f0b1cd4f?w=800&h=800&fit=crop', altText: 'Ceylon cinnamon sticks', isPrimary: true, sortOrder: 0 },
      { id: 'img-2', url: 'https://images.unsplash.com/photo-1562059390-a761a084768e?w=800&h=800&fit=crop', altText: 'Cinnamon packaging', isPrimary: false, sortOrder: 1 },
      { id: 'img-3', url: 'https://images.unsplash.com/photo-1587132137056-bfbf0166836e?w=800&h=800&fit=crop', altText: 'Cinnamon plantation', isPrimary: false, sortOrder: 2 },
    ],
    variants: [
      { id: 'var-1', sku: 'CIN-ALB-100', name: '100g Pack', price: 24.99, compareAtPrice: 34.99, stock: 500, attributes: { weight: '100g' } },
      { id: 'var-2', sku: 'CIN-ALB-250', name: '250g Pack', price: 49.99, compareAtPrice: 69.99, stock: 300, attributes: { weight: '250g' } },
      { id: 'var-3', sku: 'CIN-ALB-1KG', name: '1kg Bulk', price: 149.99, compareAtPrice: 199.99, stock: 100, attributes: { weight: '1kg' } },
    ],
    vendor: mockVendors[0],
    category: mockCategories[0],
  },
  {
    id: 'p-2',
    name: 'Handloom Silk Saree - Kanchipuram Collection',
    slug: 'handloom-silk-saree-kanchipuram',
    description:
      'Exquisite Kanchipuram silk saree woven by master artisans in Tamil Nadu. Features traditional temple border design with pure zari work. Each saree takes 15-20 days to weave by hand. Comes with matching blouse piece.',
    shortDescription: 'Traditional Kanchipuram silk with pure zari temple border',
    baseCurrency: 'USD',
    basePrice: 299.00,
    compareAtPrice: 450.00,
    averageRating: 4.9,
    totalReviews: 89,
    minOrderQty: 1,
    vendorId: 'v-2',
    categoryId: 'cat-2',
    status: 'ACTIVE',
    images: [
      { id: 'img-4', url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&h=800&fit=crop', altText: 'Silk saree', isPrimary: true, sortOrder: 0 },
      { id: 'img-5', url: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=800&h=800&fit=crop', altText: 'Saree detail', isPrimary: false, sortOrder: 1 },
    ],
    variants: [
      { id: 'var-4', sku: 'SAR-KAN-RED', name: 'Royal Red', price: 299.00, compareAtPrice: 450.00, stock: 25, attributes: { color: 'Red', material: 'Pure Silk' } },
      { id: 'var-5', sku: 'SAR-KAN-BLU', name: 'Peacock Blue', price: 319.00, compareAtPrice: 450.00, stock: 20, attributes: { color: 'Blue', material: 'Pure Silk' } },
      { id: 'var-6', sku: 'SAR-KAN-GRN', name: 'Emerald Green', price: 309.00, compareAtPrice: 450.00, stock: 18, attributes: { color: 'Green', material: 'Pure Silk' } },
    ],
    vendor: mockVendors[1],
    category: mockCategories[1],
  },
  {
    id: 'p-3',
    name: 'Natural Blue Sapphire - 2.5 Carat Certified',
    slug: 'natural-blue-sapphire-2-5ct',
    description:
      'Stunning natural blue sapphire mined from the gem pits of Ratnapura, Sri Lanka. Certified by GIA with excellent clarity and a vivid cornflower blue colour. Unheated and untreated. Perfect for engagement rings or fine jewellery.',
    shortDescription: 'GIA certified unheated Ceylon sapphire, vivid cornflower blue',
    baseCurrency: 'USD',
    basePrice: 4500.00,
    compareAtPrice: null,
    averageRating: 5.0,
    totalReviews: 23,
    minOrderQty: 1,
    vendorId: 'v-3',
    categoryId: 'cat-3',
    status: 'ACTIVE',
    images: [
      { id: 'img-6', url: 'https://images.unsplash.com/photo-1599707367790-a54bafa72705?w=800&h=800&fit=crop', altText: 'Blue sapphire', isPrimary: true, sortOrder: 0 },
      { id: 'img-7', url: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&h=800&fit=crop', altText: 'Sapphire certificate', isPrimary: false, sortOrder: 1 },
    ],
    variants: [
      { id: 'var-7', sku: 'SAP-BLU-2.5', name: '2.5 Carat', price: 4500.00, compareAtPrice: null, stock: 3, attributes: { carat: '2.5', cut: 'Oval' } },
    ],
    vendor: mockVendors[2],
    category: mockCategories[2],
  },
  {
    id: 'p-4',
    name: 'Organic Ceylon Black Tea - BOP Grade',
    slug: 'organic-ceylon-black-tea-bop',
    description:
      'Single-estate organic black tea from the Nuwara Eliya highlands. BOP (Broken Orange Pekoe) grade delivers a rich, full-bodied brew with bright golden liquor. Packed at origin for maximum freshness.',
    shortDescription: 'Single-estate highland tea, rich and full-bodied',
    baseCurrency: 'USD',
    basePrice: 18.50,
    compareAtPrice: 24.00,
    averageRating: 4.7,
    totalReviews: 215,
    minOrderQty: 1,
    vendorId: 'v-1',
    categoryId: 'cat-1',
    status: 'ACTIVE',
    images: [
      { id: 'img-8', url: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=800&h=800&fit=crop', altText: 'Ceylon black tea', isPrimary: true, sortOrder: 0 },
    ],
    variants: [
      { id: 'var-8', sku: 'TEA-BOP-100', name: '100g Tin', price: 18.50, compareAtPrice: 24.00, stock: 800, attributes: { weight: '100g' } },
      { id: 'var-9', sku: 'TEA-BOP-250', name: '250g Tin', price: 39.99, compareAtPrice: 52.00, stock: 400, attributes: { weight: '250g' } },
    ],
    vendor: mockVendors[0],
    category: mockCategories[0],
  },
  {
    id: 'p-5',
    name: 'Virgin Coconut Oil - Cold Pressed',
    slug: 'virgin-coconut-oil-cold-pressed',
    description:
      'Pure virgin coconut oil cold-pressed from fresh organic coconuts. Rich in lauric acid and MCTs. Perfect for cooking, skincare, and haircare. No additives, no bleaching, no deodorizing.',
    shortDescription: 'Pure cold-pressed organic coconut oil, multi-purpose',
    baseCurrency: 'USD',
    basePrice: 12.99,
    compareAtPrice: 18.00,
    averageRating: 4.6,
    totalReviews: 198,
    minOrderQty: 2,
    vendorId: 'v-1',
    categoryId: 'cat-5',
    status: 'ACTIVE',
    images: [
      { id: 'img-9', url: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800&h=800&fit=crop', altText: 'Coconut oil', isPrimary: true, sortOrder: 0 },
    ],
    variants: [
      { id: 'var-10', sku: 'COC-VCO-500', name: '500ml Bottle', price: 12.99, compareAtPrice: 18.00, stock: 600, attributes: { size: '500ml' } },
      { id: 'var-11', sku: 'COC-VCO-1L', name: '1 Litre Bottle', price: 22.99, compareAtPrice: 30.00, stock: 350, attributes: { size: '1L' } },
    ],
    vendor: mockVendors[0],
    category: mockCategories[4],
  },
  {
    id: 'p-6',
    name: 'Handwoven Cotton Kurta - Block Printed',
    slug: 'handwoven-cotton-kurta-block-printed',
    description:
      'Men\'s handwoven cotton kurta with traditional Rajasthani block printing. Lightweight and breathable, perfect for summer. Each piece is individually hand-printed making every kurta unique.',
    shortDescription: 'Hand block-printed cotton kurta, lightweight summer wear',
    baseCurrency: 'USD',
    basePrice: 45.00,
    compareAtPrice: 65.00,
    averageRating: 4.5,
    totalReviews: 76,
    minOrderQty: 1,
    vendorId: 'v-2',
    categoryId: 'cat-2',
    status: 'ACTIVE',
    images: [
      { id: 'img-10', url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&h=800&fit=crop', altText: 'Block printed kurta', isPrimary: true, sortOrder: 0 },
    ],
    variants: [
      { id: 'var-12', sku: 'KUR-BLK-S', name: 'Small', price: 45.00, compareAtPrice: 65.00, stock: 50, attributes: { size: 'S' } },
      { id: 'var-13', sku: 'KUR-BLK-M', name: 'Medium', price: 45.00, compareAtPrice: 65.00, stock: 80, attributes: { size: 'M' } },
      { id: 'var-14', sku: 'KUR-BLK-L', name: 'Large', price: 45.00, compareAtPrice: 65.00, stock: 60, attributes: { size: 'L' } },
      { id: 'var-15', sku: 'KUR-BLK-XL', name: 'XL', price: 45.00, compareAtPrice: 65.00, stock: 40, attributes: { size: 'XL' } },
    ],
    vendor: mockVendors[1],
    category: mockCategories[1],
  },
  {
    id: 'p-7',
    name: 'Ayurvedic Herbal Hair Oil - 7 Herb Formula',
    slug: 'ayurvedic-herbal-hair-oil-7herbs',
    description:
      'Traditional Ayurvedic hair oil infused with seven medicinal herbs including Bhringraj, Amla, Brahmi, and Neem. Promotes hair growth, prevents dandruff, and nourishes the scalp. Cold-processed in small batches.',
    shortDescription: 'Traditional 7-herb formula for hair growth and scalp health',
    baseCurrency: 'USD',
    basePrice: 16.99,
    compareAtPrice: 22.00,
    averageRating: 4.4,
    totalReviews: 312,
    minOrderQty: 1,
    vendorId: 'v-1',
    categoryId: 'cat-7',
    status: 'ACTIVE',
    images: [
      { id: 'img-11', url: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&h=800&fit=crop', altText: 'Herbal hair oil', isPrimary: true, sortOrder: 0 },
    ],
    variants: [
      { id: 'var-16', sku: 'AYU-OIL-200', name: '200ml Bottle', price: 16.99, compareAtPrice: 22.00, stock: 400, attributes: { size: '200ml' } },
    ],
    vendor: mockVendors[0],
    category: mockCategories[6],
  },
  {
    id: 'p-8',
    name: 'Handcarved Wooden Elephant - Rosewood',
    slug: 'handcarved-wooden-elephant-rosewood',
    description:
      'Beautifully hand-carved rosewood elephant by master craftsmen from Kandy. Traditional Sri Lankan design with intricate detailing. Each piece is unique and comes with a certificate of authenticity. Perfect as a decorative piece or gift.',
    shortDescription: 'Master-crafted rosewood elephant, traditional Sri Lankan artistry',
    baseCurrency: 'USD',
    basePrice: 89.00,
    compareAtPrice: 120.00,
    averageRating: 4.9,
    totalReviews: 54,
    minOrderQty: 1,
    vendorId: 'v-1',
    categoryId: 'cat-4',
    status: 'ACTIVE',
    images: [
      { id: 'img-12', url: 'https://images.unsplash.com/photo-1602523069025-d07317603ccc?w=800&h=800&fit=crop', altText: 'Wooden elephant', isPrimary: true, sortOrder: 0 },
    ],
    variants: [
      { id: 'var-17', sku: 'WOD-ELE-SM', name: 'Small (15cm)', price: 89.00, compareAtPrice: 120.00, stock: 30, attributes: { size: '15cm' } },
      { id: 'var-18', sku: 'WOD-ELE-LG', name: 'Large (30cm)', price: 189.00, compareAtPrice: 250.00, stock: 12, attributes: { size: '30cm' } },
    ],
    vendor: mockVendors[0],
    category: mockCategories[3],
  },
];
